apiVersion: v1
kind: Service
metadata:
  labels:
    app: shivamm-app-prac10
  name: shivamm-service
  namespace: default
spec:
  type: NodePort  
  ports:
    - name: http
      protocol: TCP
      port: 3000    
  selector:
    app: shivamm-app-prac10
    